/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RoomBookingSystem;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hamza
 */
public class RoomManagerGUI extends javax.swing.JFrame implements Runnable,Observer {

    private SharedData sharedData;
    
    /**
     * Creates new form RoomManagerGUI
     */
    public RoomManagerGUI(SharedData initialBookings) {
        super();
        sharedData = initialBookings;
        sharedData.addObserver(this);
        initComponents();
        updateSharedBookings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddRoom = new javax.swing.JButton();
        btnSeeBookings = new javax.swing.JButton();
        btnAddUnavailability = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBookings = new javax.swing.JTable();
        comboRoom = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spinRoomSpaces = new javax.swing.JSpinner();
        comboRoomType = new javax.swing.JComboBox<>();
        spinUnavailableFrom = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spinUnavailableUntil = new javax.swing.JSpinner();
        SimpleDateFormat spinTermBeginningModel = new SimpleDateFormat("dd/MM/yyyy");
        spinTermBeginning = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SimpleDateFormat spinTermEndingModel = new SimpleDateFormat("dd/MM/yyyy");
        spinTermEnding = new javax.swing.JSpinner();
        btnAddTermDate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Room Manager");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(389, 11, 274, 44);

        btnAddRoom.setText("Add Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddRoom);
        btnAddRoom.setBounds(40, 240, 220, 23);

        btnSeeBookings.setText("See Bookings");
        btnSeeBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeBookingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeeBookings);
        btnSeeBookings.setBounds(710, 240, 320, 23);

        btnAddUnavailability.setText("Add Unavailability");
        btnAddUnavailability.setToolTipText("");
        getContentPane().add(btnAddUnavailability);
        btnAddUnavailability.setBounds(310, 240, 300, 23);
        getContentPane().add(txtName);
        txtName.setBounds(130, 120, 130, 20);

        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 128, 70, 14);

        tableBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Name", "Date", "Time", "Booker Name", "Email", "Phone", "Notes"
            }
        ));
        jScrollPane1.setViewportView(tableBookings);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(709, 106, 320, 120);

        comboRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboRoom);
        comboRoom.setBounds(443, 125, 170, 20);

        jLabel3.setText("Room:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 130, 100, 14);

        jLabel4.setText("Spaces:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 70, 14);

        jLabel5.setText("Type:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 70, 14);

        spinRoomSpaces.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spinRoomSpaces);
        spinRoomSpaces.setBounds(130, 210, 50, 20);

        comboRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Lab", "Tutorial Room", "Lecture Theatre" }));
        getContentPane().add(comboRoomType);
        comboRoomType.setBounds(130, 170, 130, 20);

        spinUnavailableFrom.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(spinUnavailableFrom);
        spinUnavailableFrom.setBounds(441, 156, 170, 30);

        jLabel6.setText("Unavailable From:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 160, 120, 20);

        jLabel7.setText("Until:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 210, 90, 14);

        spinUnavailableUntil.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(spinUnavailableUntil);
        spinUnavailableUntil.setBounds(440, 200, 170, 30);

        spinTermBeginning.setModel(new javax.swing.SpinnerDateModel());
        spinTermBeginning.setEditor(new javax.swing.JSpinner.DateEditor(spinTermBeginning,spinTermBeginningModel.toPattern()));
        getContentPane().add(spinTermBeginning);
        spinTermBeginning.setBounds(100, 340, 150, 30);

        jLabel8.setText("Term Beginning:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 350, 77, 14);

        jLabel9.setText("Term Ending:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 410, 70, 14);

        spinTermEnding.setModel(new javax.swing.SpinnerDateModel());
        spinTermEnding.setEditor(new javax.swing.JSpinner.DateEditor(spinTermEnding,spinTermEndingModel.toPattern()));
        getContentPane().add(spinTermEnding);
        spinTermEnding.setBounds(100, 400, 150, 30);

        btnAddTermDate.setText("Add Term Dates");
        btnAddTermDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTermDateActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddTermDate);
        btnAddTermDate.setBounds(10, 450, 240, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeeBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeBookingsActionPerformed
        //tbi
    }//GEN-LAST:event_btnSeeBookingsActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        
        int spaces = Integer.parseInt(spinRoomSpaces.getValue().toString());
        if (spaces > 0)
        {
            int selectedIndex = comboRoomType.getSelectedIndex();
            TypeOfRoom roomType = (selectedIndex == 0) ? TypeOfRoom.COMPUTER_LAB : (selectedIndex == 1) ? TypeOfRoom.TUTORIAL_ROOM : (selectedIndex == 2) ? TypeOfRoom.LECTURE_THEATRE : null;
            OneRoom newRoom = new OneRoom(txtName.getText(),roomType,spaces);
            sharedData.addRoom(newRoom);
            JOptionPane.showMessageDialog(null, "Room Added!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Room Not Added! Number of Spaces must be 1 or more!");
        }
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnAddTermDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTermDateActionPerformed
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String textTermBeginning = ((JSpinner.DefaultEditor)spinTermBeginning.getEditor()).getTextField().getText();
        String textTermEnding = ((JSpinner.DefaultEditor)spinTermEnding.getEditor()).getTextField().getText();

        LocalDate termBeginningDate = LocalDate.parse(textTermBeginning,formatter);
        LocalDate termEndingDate = LocalDate.parse(textTermEnding,formatter);
        if (termEndingDate.isAfter(termBeginningDate))
        {
            OneTerm newTerm = new OneTerm(termBeginningDate,termEndingDate);
            sharedData.addTerm(newTerm);
            JOptionPane.showMessageDialog(null, "Term Added!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Term Not Added. Ending Date Must Be After Beginning!");
        }
    }//GEN-LAST:event_btnAddTermDateActionPerformed

    
        @Override
    public void run() {
        
        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RoomManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RoomManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RoomManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RoomManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        this.setVisible(true);
                
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RoomManagerGUI().setVisible(true);
//            }
//        });
    }

    @Override
    public void update(Observable o, Object arg) {
        updateSharedBookings();
    }
    
    public void updateSharedBookings()
    {
        addRoomsToComboBox();
        addBookingsToTable();
    }
    
    public void addRoomsToComboBox()
    {
        ArrayList<OneRoom> rooms = sharedData.getTheRooms();
        String[] arr = new String[rooms.size()];
        for (int i = 0; i < arr.length;i++)
        {
            arr[i] = rooms.get(i).getRoomName();
        }
        comboRoom.setModel(new DefaultComboBoxModel<String>(arr));
    }
    
    public void addBookingsToTable()
    {
        ArrayList<OneBooking> bookings = sharedData.getTheBookings();
        DefaultTableModel model = (DefaultTableModel) tableBookings.getModel();
        model.setRowCount(0);
        for (OneBooking booking : bookings)
        {
            model.addRow(new Object[]{booking.getRoomName(),booking.getBookingDate().toString(),booking.getBookingTime().toString(),booking.getBookerName(),booking.getBookerEmail(),booking.getBookerPhone(),booking.getBookingNotes()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnAddTermDate;
    private javax.swing.JButton btnAddUnavailability;
    private javax.swing.JButton btnSeeBookings;
    private javax.swing.JComboBox<String> comboRoom;
    private javax.swing.JComboBox<String> comboRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinRoomSpaces;
    private javax.swing.JSpinner spinTermBeginning;
    private javax.swing.JSpinner spinTermEnding;
    private javax.swing.JSpinner spinUnavailableFrom;
    private javax.swing.JSpinner spinUnavailableUntil;
    private javax.swing.JTable tableBookings;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables


}
